---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '12.2.1'

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list: ['recipe[apt]']
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_ubuntu-14.04_chef-provisionerless.box
  run_list: ['recipe[apt]']
- name: centos-6.6
  driver_config:
    box: opscode-centos-6.6
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_centos-6.6_chef-provisionerless.box
- name: centos-7.1
  driver_config:
    box: opscode-centos-7.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_centos-7.1_chef-provisionerless.box

suites:
- name: default
  run_list: ['recipe[localshop]']
