AllCops:
  Include:
    - '**/Berksfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Thorfile'
    - '**/Guardfile'
  Exclude:
    - 'vendor/**/*'
    - '**/metadata.rb'

Metrics/LineLength:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
