source 'https://rubygems.org'

gem 'rake'
gem 'chefspec', '~> 4.3.0'
gem 'foodcritic', '~> 4.0.0'
gem 'rubocop', '~> 0.30.0'
gem 'rubocop-checkstyle_formatter'
gem 'fauxhai'
gem 'berkshelf', '~> 3.3.0'
gem 'test-kitchen', '~> 1.4.0'
gem 'kitchen-vagrant'
gem 'thor-scmversion'
gem 'chef', '= 12.2.1'
